### ISSUE TITLE
Sample video

### ISSUE THREAD

**Issue by vanlooverenkoen** [reiniiriarios/stream-deck-billables-harvest#2]
Tanks for your great work so far! It looks really promising. I considering to build a stream deck just to have this. I thought of building it myself but this has everting I need. Is it possible to create a sample video and add it to the readme file so it is easy to see what all the features are exactly. And how it actually works.

**Comment by reiniiriarios** [comment]
Hi @vanlooverenkoen! I've added [a couple of screenshots and a photo](https://github.com/reiniiriarios/stream-deck-billables-harvest#preview), but a video is far more time than I want to invest.

It's really quite a basic app and should only take a few moments to fully explore (after pasting in your API token and account ids).

**Comment by vanlooverenkoen** [comment]
Hi thanks! I currently don't have a stream deck, I am considering to buy one. Looks really nice. I still have a couple of questions:
If I have 2 projects with each 2 tasks. Is it possible to have 4 buttons to start a tracking for each combo?

**Comment by reiniiriarios** [comment]
Yes! Absolutely. Regardless of plugin, each button is its own self-contained instance with its own config, settings, etc. (This means you have to have the API keys in each button, but you can quite easily copy/paste buttons and then edit.)

![image](https://github.com/reiniiriarios/stream-deck-billables-harvest/assets/80431903/50f9d5a6-5d1a-4298-8f91-35c3ad8073a9)

I see you're a developer... I get a lot of use out of the [GitHub API Plugin](https://apps.elgato.com/plugins/com.github.guyb7.github-api-streamdeck-plugin) / [guyb7/github-api-streamdeck-plugin](https://github.com/guyb7/github-api-streamdeck-plugin) as well.

**Comment by vanlooverenkoen** [comment]
Thanks, I guess it is time to order a streamdeck 😅
