### ISSUE TITLE
Support for 01:30 hour format

### ISSUE THREAD

**Issue by vanlooverenkoen** [reiniiriarios/stream-deck-billables-harvest#3]
I just bought the stream deck mk.2! And I love it! I have 15 harvest items setup so it is easy to switch between tasks on my desk. Also have an easier way of getting a detailed report for clients where I spent time. 

I was just wondering why the time formatting for the timers are so strange. 

0m
10m
50m
-> these are fine.

But the moment we go over an hour the formatting changes to decimals.
1.10h -> 1h 6m
1.5h -> 1h 30m

I would like to have the option to use the same formatting as harvest would be more streamlined. 

I would opt for these structures

00:00
00:10
01:06
01:30

What do you think of this approach?

**Comment by reiniiriarios** [comment]
Awesome!

This is a great idea. I'm putting this on my todo list.

**Comment by vanlooverenkoen** [comment]
I'm currently on a tight deadline for a project, but I will checkout the code as well. I have some other ideas as wel, not sure if it is possible, i will do some investigation first

**Comment by reiniiriarios** [comment]
Time format option added: https://github.com/reiniiriarios/stream-deck-billables-harvest/commit/9a98cfc427e37ed14531aea9d7af332e10c97857

**Comment by vanlooverenkoen** [comment]
I can see 2 issues with the new 00:00 formatting.

If I have logged some hours it will map to 9999999

And 0 maps to 00:0 onstead of 0:00

![PXL_20230802_063848315.jpg](https://github.com/reiniiriarios/stream-deck-billables-harvest/assets/21172855/8eb5be2a-22ce-4b66-b56d-8bd7e0e7d662)

**Comment by reiniiriarios** [comment]
That is frustrating. And that's what I get for rushing through that feature. 😅  A fix should be on the Stream Deck store soon.

Fix in: https://github.com/reiniiriarios/stream-deck-billables-harvest/releases/tag/v0.4.0

**Comment by vanlooverenkoen** [comment]
Thanks, let me know when it is live, so I can test again :)

**Comment by reiniiriarios** [comment]
The update should now be on the stream deck store. It may take a bit for the update to propagate.

**Comment by vanlooverenkoen** [comment]
Works like a charm! Thanks!
