### ISSUE TITLE
Daily harvest overview

### ISSUE THREAD

**Issue by vanlooverenkoen** [reiniiriarios/stream-deck-billables-harvest#5]
It would be nice to have a basic widget to see the total performed time of the day.

It should not be needed to have forecast as well for this I guess.

For this day it would be: `04:52`

![image](https://github.com/reiniiriarios/stream-deck-billables-harvest/assets/21172855/72bcc386-7c55-43fa-96a8-c81fc4975cf1)

**Comment by reiniiriarios** [comment]
Great idea! No forecast needed. Putting this on my todo list!

**Comment by reiniiriarios** [comment]
This feature is now updated in the [Stream Deck store](https://apps.elgato.com/plugins/me.reinii.harvest-billables).

**Comment by vanlooverenkoen** [comment]
I receive H0400 errors

- Today
- All Hours
